### ISSUE TITLE
Angular 5

### ISSUE THREAD

**Issue by plattdl** [manishit56/Angular4-JsonEditor#5]
Are there any plans to update this to Angular 5? I am getting a critical dependency warning regarding es5 after I upgraded to Angular 5 in my app. The warning is coming from this package. 

Thanks for your work!

**Comment by manishit56** [comment]
I will try to update as soon as possible. Thanks for the information.

**Comment by elsticky** [comment]
Next to this warning I also get following error:
Uncaught Error: Unexpected value 'Ng4JsonEditorModule' imported by the module 'AppModule'. Please add a @NgModule annotation. 

On Angular4 it was fine so I think it's due to some incompatibility?

**Comment by mariohmol** [comment]
Hi.. i took this project and renamed to just angular.. and basicly changed versions to angular5 

* https://www.npmjs.com/package/ang-jsoneditor

Thanks @manishit56  for the awesome work

**Comment by kapiladiyecha** [comment]
Hi @mariohmol,

https://www.npmjs.com/package/ang-jsoneditor is also failing during serve & build.

Not able to open an issue, is this under development or working project?


Errors:

```
Date: 2018-02-22T05:54:48.059Z
ERROR in ./node_modules/ang-jsoneditor/index.tsHash: 820098b3f85c8ee25cfd

Time: 16075Module build failed: Error: C:\Kapil\XXXXXXXX\YYYYYYYY\node_modules\ang-jsoneditor\index.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.ms

chunk {inlineThe missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).} inline.bundle.js (inline) 29.2 kB 
[entry] [rendered]    at AngularCompilerPlugin.getCompiledFile (C:\Kapil\XXXXXXXX\YYYYYYYY\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:674:23)

chunk {main    at plugin.done.then (C:\Kapil\XXXXXXXX\YYYYYYYY\node_modules\@ngtools\webpack\src\loader.js:467:39)} main.bundle.js
 (main) 1.65 MB     at <anonymous>
[initial] [rendered]    at process._tickCallback (internal/process/next_tick.js:188:7)

chunk {polyfillsERROR in ./node_modules/ang-jsoneditor/jsoneditor/jsoneditor.component.ts} 
polyfills.bundle.js (polyfills) 953 kB [initial] [rendered]Module build failed: Error: C:\Kapil\XXXXXXXX\YYYYYYYY\node_modules\ang-jsoneditor\jsoneditor\jsoneditor.component.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.

chunk {The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).scripts} 
scripts.bundle.js (scripts) 3.15 MB     at AngularCompilerPlugin.getCompiledFile (C:\Kapil\XXXXXXXX\YYYYYYYY\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:674:23)[initial]
 [rendered]
    at plugin.done.then (C:\Kapil\XXXXXXXX\YYYYYYYY\node_modules\@ngtools\webpack\src\loader.js:467:39)chunk {
styles}     at <anonymous>styles.bundle.js
 (styles) 929 kB [initial] [rendered]    at process._tickCallback (internal/process/next_tick.js:188:7)

chunk {vendor} vendor.bundle.js (vendor) 22 MB [initial] [rendered]

webpack: Failed to compile.
```


Thanks

**Comment by kapiladiyecha** [comment]
Workaround for above error:

src/**tsconfig.app.json**

.....
.....
```
"include": [
    "../src/**/*",
    "../node_modules/ang-jsoneditor/index.ts",
    "../node_modules/ang-jsoneditor/jsoneditor/jsoneditor.component.ts"
  ]
```
.....
.....

**Comment by mariohmol** [comment]
Thanks! 

I included the issues in the repo 
* https://github.com/mariohmol/ang-jsoneditor/ 

Added the i18n support 
* https://github.com/josdejong/jsoneditor/pull/514

And included your change in tsconfig. This was working before, but event after your suggestion it keeps working.. as this does not work in the component structure.. i pushed anyway!

bests

**Comment by manishit56** [comment]
Updated master with Angular 5 support
